[package]
name = "nodedup"
version = "2.0.0"
edition = "2021"
license = "MIT"
description = "Find duplicate JS dependencies in a given folder"

[dependencies]
walkdir = "2.5.0"
serde_json = "1.0.117"
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
regex = "1.10.5"